language: go
sudo: false

go:
  - "1.10.x"
  - master

git:
  depth: 1

script:
  - make test

install:
  - go get -t ./...
  - pyenv install -f 3.6.3
  - pyenv global 3.6.3
  - python3 -m pip install --user -r tests/requirements.txt
  - go build

branches:
  only:
    - master

notifications:
  email: false
